{{- if .Values.query.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: {{ .Values.image.query.name  }}
        image: "{{ .Values.image.query.repository }}:{{ .Values.image.query.tag }}"
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: {{ .Chart.Name }}-configmap

      - name: {{ .Values.image.redis.name  }}
        image: "{{ .Values.image.redis.repository }}:{{ .Values.image.redis.tag }}"
        ports:
        - containerPort: 6379
        env:
        - name: MASTER_REDIS_HOST
          value: redis-stack.observability-datamesh.svc.cluster.local
        - name: MASTER_REDIS_PORT
          value: "6379"
        - name: REDISCLI_AUTH
          value: "7b7k36kBTGdvUE5G"
        volumeMounts:
        - mountPath: /var/log/redis
          name: redis-log
      volumes:
      - name: redis-log
        emptyDir: {}
{{- end }}