replicaCount: 1

image:
  repository: redis/redis-stack
  tag: "latest"
  pullPolicy: IfNotPresent
namespace: observability-edge
service:
  type: ClusterIP
  port: 6379

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"

nodeSelector: {}
tolerations: []
affinity: {}
