{{- if and .Values.rbac.enabled .Values.rbac.serviceAccount.create -}}

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-sa
  namespace: {{ .Values.trino-coordinator.namespace }}

{{- end }}