# Redis configuration example
bind 0.0.0.0
protected-mode no
port 6379
daemonize no
logfile "/var/log/redis/redis.log"
dbfilename dump.rdb
dir /data
# save 60 1 only for snapshot
save ""
appendonly yes
loglevel debug