apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: central-redis
    release: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
  
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 6379
    protocol: TCP
  selector:
    app: central-redis
    release: {{ .Release.Name }}
